import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:path/path.dart';
import 'package:path_provider/path_provider.dart';
import 'package:sqflite_common_ffi/sqflite_ffi.dart';

import 'migration_engine.dart';

/// Singleton database lifecycle manager for Thaili.
///
/// Responsibilities:
/// - Opens the SQLite database file at the platform-correct path.
/// - Configures Write-Ahead Logging (WAL) for maximum read/write concurrency.
/// - Delegates schema creation and incremental upgrades to [MigrationEngine].
///
/// Note on encryption: standard `sqflite` uses an unencrypted SQLite file,
/// which is safe within the Android app sandbox (direct file access requires
/// root). The master encryption key is generated by [DatabaseSecurity] and
/// stored in the hardware-backed Android Keystore for forward-compatible
/// integration with SQLCipher if the project requirements evolve.
///
/// Usage:
/// ```dart
/// final db = await AppDatabase.instance.database;
/// ```
class AppDatabase {
  AppDatabase._();
  static final AppDatabase instance = AppDatabase._();

  Database? _db;
  static const String _dbName = 'thaili.db';
  static const int _dbVersion = 2;

  /// Returns the open [Database], initializing it on first access.
  Future<Database> get database async {
    if (_db != null && _db!.isOpen) return _db!;
    _db = await _initialize();
    return _db!;
  }

  Future<Database> _initialize() async {
    // On Windows/Linux desktop, initialize the FFI-backed SQLite engine.
    if (!kIsWeb && (Platform.isWindows || Platform.isLinux)) {
      sqfliteFfiInit();
      databaseFactory = databaseFactoryFfi;
    }

    String dbPath;
    final isTest = Platform.environment.containsKey('FLUTTER_TEST');
    if (!kIsWeb && !isTest && (Platform.isWindows || Platform.isLinux || Platform.isMacOS)) {
      // In production desktop apps, store in AppData/Application Support so non-admin users have full write access
      final appSupportDir = await getApplicationSupportDirectory();
      final dbDir = Directory(join(appSupportDir.path, 'databases'));
      if (!await dbDir.exists()) {
        await dbDir.create(recursive: true);
      }
      dbPath = join(dbDir.path, _dbName);
    } else {
      final databasesPath = await getDatabasesPath();
      dbPath = join(databasesPath, _dbName);
    }

    debugPrint('[AppDatabase] Opening database at: $dbPath');

    final db = await openDatabase(
      dbPath,
      version: _dbVersion,
      onCreate: (db, version) async {
        // onCreate fires on a brand-new installation.
        debugPrint('[AppDatabase] onCreate — applying migrations 1..$version');
        await MigrationEngine.runMigrations(db, 0, version);
      },
      onUpgrade: (db, oldVersion, newVersion) async {
        // onUpgrade fires when the app version increases.
        debugPrint('[AppDatabase] onUpgrade $oldVersion → $newVersion');
        await MigrationEngine.runMigrations(db, oldVersion, newVersion);
      },
      onOpen: (db) async {
        // Re-apply PRAGMAs every open — they are not persisted between sessions.
        await _configurePragmas(db);
        debugPrint('[AppDatabase] Database opened successfully.');
      },
    );

    return db;
  }

  /// Configures high-concurrency and safety SQLite PRAGMAs.
  ///
  /// - `WAL` mode: Readers never block writers; multiple reads run concurrently.
  /// - `NORMAL` synchronous: Durability on most crashes with much better speed
  ///   than FULL while still being safer than OFF.
  /// - `foreign_keys ON`: Enforces referential integrity at the DB level.
  /// - `busy_timeout 5000`: Prevents "database is locked" errors under load.
  static Future<void> _configurePragmas(Database db) async {
    await db.rawQuery('PRAGMA journal_mode = WAL');
    await db.rawQuery('PRAGMA synchronous = NORMAL');
    await db.rawQuery('PRAGMA foreign_keys = ON');
    await db.rawQuery('PRAGMA busy_timeout = 5000');
    await db.rawQuery('PRAGMA cache_size = -4000'); // 4 MB page cache
  }

  /// Runs an SQLite integrity check. Returns `'ok'` if the database is healthy.
  Future<String> integrityCheck() async {
    final db = await database;
    final result = await db.rawQuery('PRAGMA integrity_check');
    return (result.first.values.first as String?) ?? 'error';
  }

  /// Closes the database connection. Primarily used in tests and app shutdown.
  Future<void> close() async {
    if (_db != null && _db!.isOpen) {
      await _db!.close();
      _db = null;
      debugPrint('[AppDatabase] Database closed.');
    }
  }
}
